### ISSUE TITLE
rake snorby:soft_reset task is broken

### ISSUE THREAD

**Issue by rvineyard** [Snorby/snorby#102]
So I logged in to Snorby this morning and noticed that yet again my dashboard was "stuck" - events were flowing in but the numbers and graphs were not getting updated, this time not even after manually restarting the delayed_job and CacheJob tasks. I did a bit of digging and ran across the :soft_reset task in lib/tasks/snorby.rake, however in its present form it is broken.

On line 63, the code currently reads:
`Snorby::Worker.reset_cache(:all, true)`

Considering that the :reset_cache method is defined in the Jobs class, this is probably more appropriate:
`Snorby::Jobs.reset_cache(:all, true)`

Now, after making that change, things initially look as I would expect, but then it errors out with the dreaded "undefined method `ip_src' for nil:NilClass" error that I haven't otherwise seen since the upgrade to 2.3.2.

I say upgrade, but really it was a pave and rebuild - I dropped my snort database, deleted my old snorby directory, pulled a fresh copy from the git master and started clean with a "rake snorby:setup".

Here's a trace of my modified :soft_reset task:

```
bash-3.2$ rake --trace snorby:soft_reset

<--- snip --->

Processing Batch 1 of 1...
Sensor 12: - fetching sensor metrics
Sensor 12: - building proto counts
Sensor 12: - fetch_event_count
Sensor 12: - fetching tcp count
Sensor 12: - fetching udp count
Sensor 12: - fetching icmp count
Sensor 12: - fetching severity metrics
Sensor 12: - fetching src ip metrics
rake aborted!
undefined method `ip_src' for nil:NilClass
/var/www/snorby/ezprint/ruby/1.9.1/gems/activesupport-3.0.5/lib/active_support/whiny_nil.rb:48:in `method_missing'
/var/www/snorby/lib/snorby/jobs/cache_helper.rb:144:in `block in fetch_src_ip_metrics'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-core-1.1.0/lib/dm-core/collection.rb:507:in `block in each'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-core-1.1.0/lib/dm-core/support/lazy_array.rb:411:in `block in each'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-core-1.1.0/lib/dm-core/support/lazy_array.rb:411:in `each'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-core-1.1.0/lib/dm-core/support/lazy_array.rb:411:in `each'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-core-1.1.0/lib/dm-core/collection.rb:504:in `each'
/var/www/snorby/lib/snorby/jobs/cache_helper.rb:144:in `group_by'
/var/www/snorby/lib/snorby/jobs/cache_helper.rb:144:in `fetch_src_ip_metrics'
/var/www/snorby/lib/snorby/jobs/daily_cache_job.rb:140:in `block in build_cache'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-chunked_query-0.3.0/lib/dm-chunked_query/chunks.rb:99:in `block in each'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-chunked_query-0.3.0/lib/dm-chunked_query/chunks.rb:98:in `times'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-chunked_query-0.3.0/lib/dm-chunked_query/chunks.rb:98:in `each'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-chunked_query-0.3.0/lib/dm-chunked_query/mixin.rb:46:in `each_chunk'
/var/www/snorby/lib/snorby/jobs/daily_cache_job.rb:125:in `build_cache'
/var/www/snorby/lib/snorby/jobs/daily_cache_job.rb:41:in `block in perform'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-core-1.1.0/lib/dm-core/collection.rb:507:in `block in each'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-core-1.1.0/lib/dm-core/support/lazy_array.rb:411:in `block in each'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-core-1.1.0/lib/dm-core/support/lazy_array.rb:411:in `each'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-core-1.1.0/lib/dm-core/support/lazy_array.rb:411:in `each'
/var/www/snorby/ezprint/ruby/1.9.1/gems/dm-core-1.1.0/lib/dm-core/collection.rb:504:in `each'
/var/www/snorby/lib/snorby/jobs/daily_cache_job.rb:39:in `perform'
/var/www/snorby/lib/snorby/jobs.rb:103:in `reset_cache'
/var/www/snorby/lib/tasks/snorby.rake:63:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19:in `<main>'
Tasks: TOP => snorby:soft_reset
```
